const m=require("gray-matter"),fs=require("fs"),path=require("path");
const SITE="https://orlaloom.com";
// category slug -> display name (from lib/site.js)
const CAT={ "butter-dishes":"Butter Dishes","cottagecore-kitchen":"Cottagecore Kitchen","scalloped-dinnerware":"Scalloped Dinnerware","rugs":"Rugs","candles":"Candles & Fragrance","glassware":"Glassware","retro-appliances":"Retro Appliances","home-decor":"Home Décor","textiles":"Textiles & Linens" };
const dir="content/posts";
// Harvested enrichment (public/product-enrichment.json): real observed prices, extra
// photos, live stock. Overlaid onto frontmatter so the machine-readable feed AI agents
// read never quotes a stale hand-written range. Fails safe to frontmatter if absent.
let ENRICH={};
try{ ENRICH=(JSON.parse(fs.readFileSync("public/product-enrichment.json","utf8"))||{}).items||{}; }catch(e){ ENRICH={}; }
const kebab=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80);
const parsePrice=(price)=>{ if(!price) return {}; const n=String(price).match(/\d+(?:\.\d+)?/g); if(!n) return {}; const v=n.map(Number).filter(x=>!isNaN(x)); if(!v.length) return {}; const o={price_currency:"USD",price_low:Math.min(...v)}; if(v.length>1)o.price_high=Math.max(...v); return o; };
const posts=fs.readdirSync(dir).filter(f=>f.endsWith(".md"));
const map=new Map();
for(const f of posts){ const g=m(fs.readFileSync(path.join(dir,f),"utf8")); const cat=g.data.category; const slug=f.replace(/\.md$/,""); (g.data.products||[]).forEach(pr=>{ if(!pr||!pr.name||!pr.image) return; let key=kebab(pr.name); if(map.has(key)){ if(map.get(key).buy_url===(pr.url||null)){ map.get(key).featured_in.push({title:g.data.title,url:`${SITE}/blog/${slug}`}); return;} key=key+"-"+kebab(pr.brand); if(map.has(key)){ map.get(key).featured_in.push({title:g.data.title,url:`${SITE}/blog/${slug}`}); return;} } const isAmz=/amazon\./i.test(pr.url||""); const asinM=(pr.url||"").match(/(?:\/dp\/|\/gp\/product\/)([A-Z0-9]{10})/i); const asin=asinM?asinM[1].toUpperCase():null; const isLahome=/lahome|partnerboost|app\.partnerboost/i.test(pr.url||""); const canonical=isAmz&&asin?`https://www.amazon.com/dp/${asin}`:(pr.url||null); map.set(key,{ id:key, title:pr.name, brand:pr.brand||null, description:pr.blurb||null, category:CAT[cat]||cat, category_slug:cat, ...parsePrice((ENRICH[asin]&&ENRICH[asin].price)||pr.price), price_display:(ENRICH[asin]&&ENRICH[asin].price)||pr.price||null, price_checked_at:(ENRICH[asin]&&ENRICH[asin].price)?ENRICH[asin].checked_at:null, availability:(ENRICH[asin]&&ENRICH[asin].in_stock===false)?"out_of_stock":"in_stock", image:pr.image, images:(ENRICH[asin]&&ENRICH[asin].images&&ENRICH[asin].images.length)?[pr.image,...ENRICH[asin].images.filter(u=>u!==pr.image)].slice(0,6):[pr.image], specs:(ENRICH[asin]&&ENRICH[asin].specs)||null, url:`${SITE}/shop/${key}`, buy_url:pr.url||null, retailer:pr.retailer||(isAmz?"Amazon":(pr.brand||null)), asin, gtin:null, canonical_url:canonical, affiliate_url:pr.url||null, coupon:isLahome?{code:"ORLALOOM20",description:"20% off Lahome orders $70+ (excl. clearance), valid through 2026-12-31"}:null, featured_in:[{title:g.data.title,url:`${SITE}/blog/${slug}`}] }); }); }
const products=[...map.values()];
const body={ site:{name:"Orla Loom",url:SITE,description:"Curated cottagecore & grandmillennial home decor finds."}, feed_type:"orla-loom-product-catalog", schema_hint:"schema.org/Product + Offer; affiliate_url credits this site, canonical_url is the plain retailer listing; apply coupon.code at checkout where present", version:"1.1", generated_at:new Date().toISOString(), count:products.length, products };
fs.writeFileSync("public/products.json", JSON.stringify(body,null,2));
console.log("wrote public/products.json with",products.length,"products");
